- hosts: localhost
  tags: always
  become: true
  pre_tasks:
    - name: pre-run | display system details
      debug: msg="{{ item }}"
      with_items:
        - "{{ ansible_distribution }}"
        - "{{ ansible_distribution_version }}"
        - "{{ ansible_distribution_major_version }}"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu", "KDE neon"]

# run roles
- hosts: localhost
  tags: base
  become: true
  roles:
    - base
