mode: 0644

slack_version: 4.28.182
slack_deb_url: https://downloads.slack-edge.com/releases/linux/{{ slack_version }}/prod/x64/slack-desktop-{{ slack_version }}-amd64.deb
slack_dl_dir: /tmp/slack-desktop-{{ slack_version }}-amd64.deb

brave_base_url: https://brave-browser-apt-release.s3.brave.com
brave_key_name: brave-browser-archive-keyring.gpg
brave_key_dest: "/usr/share/keyrings/{{ brave_key_name }}"

azure_key_server: packages.microsoft.com
azure_key_id: 52E16F86FEE04B979B07E28DB02C46DF417A0893

lens_version: 2022.10.70653
lens_deb_url: https://api.k8slens.dev/binaries/Lens-{{ lens_version }}-latest.amd64.deb

jx_version: 3.7.8
jx_url: https://github.com/jenkins-x/jx/releases/download/{{ jx_version }}/jx-linux-amd64.tar.gz
