slack_version: 4.28.182
slack_deb_url: https://downloads.slack-edge.com/releases/linux/{{ slack_version }}/prod/x64/slack-desktop-{{ slack_version }}-amd64.deb
slack_dl_dir: /tmp/slack-desktop-{{ slack_version }}-amd64.deb
