- name: Software | azure-cli | Add Repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ stable main"
    state: present
  when: ansible_distribution in ["Debian", "Ubuntu", "KDE neon"]

- name: Software | azure-cli | Install Package
  package:
    name: azure-cli
    state: present
  when: ansible_distribution in ["Debian", "Ubuntu", "KDE neon"]
