- name: Software | brave-browser | Add Repository Key
  get_url:
    url: "{{ brave_base_url }}/{{ brave_key_name }}"
    dest: "{{ brave_key_dest }}"
    mode: 0644
  when: ansible_distribution in ["Debian", "Ubuntu", "KDE neon"]

- name: Software | brave-browser | Add Repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/{{ brave_key_name }} arch=amd64] {{ brave_base_url }} stable main"
    state: present
    filename: brave-browser
  when: ansible_distribution in ["Debian", "Ubuntu", "KDE neon"]

- name: Software | brave-browser | Install Package
  apt:
    name: brave-browser
    state: present
    force_apt_get: yes
    update_cache: yes
