- name: System Setup | Utilities | Install Utility Packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - apt-transport-https
      - curl
      - rsync
      - wget
      - gdebi
