- name: Software | slack-desktop | Check If Present
  command: dpkg-query -W slack-desktop
  register: check_slack_deb
  failed_when: check_slack_deb.rc > 1
  changed_when: check_slack_deb.rc == 1
  when: ansible_distribution in ["Debian", "Ubuntu", "KDE neon"]

- name: Software | slack-desktop | Install
  apt:
    deb: "{{ slack_dl_dir }}"
    state: present
  when: (ansible_distribution in ["Debian", "Ubuntu", "KDE neon"]) or (check_lens_deb.rc == 1)
