- name: Software | slack-desktop | Check exists
  command: dpkg-query -W slack-desktop
  register: check_slack_deb
  failed_when: check_slack_deb.rc > 1
  changed_when: check_slack_deb.rc == 1
  when: ansible_distribution in ["Debian", "Ubuntu", "KDE neon"]

- name: Software | slack-desktop | Download
  get_url:
    url: "{{ slack_deb_url }}"
    dest: "{{ slack_dl_dir }}"
    mode: 0644
  when: (ansible_distribution in ["Debian", "Ubuntu", "KDE neon"]) or (check_slack_deb.rc == 1)

- name: Software | slack-desktop | Install Package
  apt: deb="{{ slack_dl_dir }}"
  when: (ansible_distribution in ["Debian", "Ubuntu", "KDE neon"]) or (check_slack_deb.rc == 1)
