- name: Software | teams | Add Key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: ansible_distribution in ["Debian", "Ubuntu", "KDE neon"]

- name: Software | teams | Add Repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main"
    state: present
    filename: teams
    update_cache: yes
  when: ansible_distribution in ["Debian", "Ubuntu", "KDE neon"]

- name: Software | teams | Install Package
  apt:
    name: teams
    state: present
    force_apt_get: yes
    update_cache: yes
  when: ansible_distribution in ["Debian", "Ubuntu", "KDE neon"]
