- name: Install zsh
  apt:
    name: zsh
    state: latest
  become: yes

- name: Install oh my zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Install PowerLevel10k theme
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1

- name: Copy zshrc
  copy:
    src: zsh/zshrc
    dest: ~/.zshrc
    mode: 0644

- name: Copy powerlevel10
  copy:
    src: zsh/p10k.zsh
    dest: ~/.p10k.zsh
    mode: 0644
